import { NextRequest, NextResponse } from 'next/server'
import { createAdminSupabase } from '@/lib/supabase'

export async function POST(req: NextRequest) {
  try {
    const body = await req.json()
    const { title, description, duration_minutes, location, time_slots, participants, send_emails } = body

    if (!title || !time_slots?.length || !participants?.length) {
      return NextResponse.json({ error: 'Missing required fields' }, { status: 400 })
    }

    const supabase = createAdminSupabase()

    // 1. Create the poll
    const { data: poll, error: pollErr } = await supabase
      .from('scheduling_polls')
      .insert({
        title,
        description,
        duration_minutes: duration_minutes || 30,
        location: location || 'zoom',
        created_by: 'cameron@neuroprogeny.com', // TODO: auth-based
        status: 'active',
      })
      .select()
      .single()

    if (pollErr) {
      console.error('Poll creation error:', pollErr)
      return NextResponse.json({ error: 'Failed to create poll' }, { status: 500 })
    }

    // 2. Create time slots
    const slotInserts = time_slots.map((s: { start_time: string; end_time: string }) => ({
      poll_id: poll.id,
      start_time: s.start_time,
      end_time: s.end_time,
    }))

    const { error: slotErr } = await supabase
      .from('poll_time_slots')
      .insert(slotInserts)

    if (slotErr) {
      console.error('Slot creation error:', slotErr)
      // Clean up
      await supabase.from('scheduling_polls').delete().eq('id', poll.id)
      return NextResponse.json({ error: 'Failed to create time slots' }, { status: 500 })
    }

    // 3. Create participants (tokens auto-generated by DB default)
    const participantInserts = participants.map((p: { name: string; email: string }) => ({
      poll_id: poll.id,
      name: p.name,
      email: p.email,
    }))

    const { data: createdParticipants, error: partErr } = await supabase
      .from('poll_participants')
      .insert(participantInserts)
      .select()

    if (partErr) {
      console.error('Participant creation error:', partErr)
      return NextResponse.json({ error: 'Failed to create participants' }, { status: 500 })
    }

    // 4. Send email invites if requested
    if (send_emails && createdParticipants) {
      const baseUrl = process.env.NEXT_PUBLIC_APP_URL || req.nextUrl.origin

      for (const participant of createdParticipants) {
        const voteUrl = `${baseUrl}/poll/${poll.id}?token=${participant.token}`

        // Send via SendGrid (when configured)
        if (process.env.SENDGRID_API_KEY) {
          try {
            await sendInviteEmail({
              to: participant.email,
              name: participant.name,
              pollTitle: title,
              voteUrl,
              createdBy: 'Cameron Allen',
            })

            // Log the email
            await supabase.from('poll_email_log').insert({
              poll_id: poll.id,
              participant_id: participant.id,
              email_type: 'invite',
              to_email: participant.email,
              subject: `When are you available? ${title}`,
              status: 'sent',
            })
          } catch (emailErr) {
            console.error(`Failed to email ${participant.email}:`, emailErr)
          }
        }
      }
    }

    // Return poll info + participant voting URLs
    const baseUrl = process.env.NEXT_PUBLIC_APP_URL || req.nextUrl.origin
    const votingLinks = createdParticipants?.map(p => ({
      name: p.name,
      email: p.email,
      voting_url: `${baseUrl}/poll/${poll.id}?token=${p.token}`,
    }))

    return NextResponse.json({
      poll_id: poll.id,
      status: 'active',
      voting_links: votingLinks,
      admin_url: `${baseUrl}/admin`,
      message: send_emails && process.env.SENDGRID_API_KEY
        ? 'Poll created and invites sent!'
        : 'Poll created. Copy the voting links below to share manually.',
    })

  } catch (err) {
    console.error('Create poll error:', err)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}

// GET - List all polls (admin)
export async function GET() {
  try {
    const supabase = createAdminSupabase()

    const { data: polls, error } = await supabase
      .from('scheduling_polls')
      .select(`
        *,
        poll_time_slots (id, start_time, end_time, available_count, total_responses, score),
        poll_participants (id, name, email, has_responded, responded_at)
      `)
      .order('created_at', { ascending: false })

    if (error) {
      return NextResponse.json({ error: 'Failed to fetch polls' }, { status: 500 })
    }

    return NextResponse.json({ polls })
  } catch (err) {
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}


// ─── SendGrid Email Helper ──────────────────────────────────
async function sendInviteEmail(params: {
  to: string
  name: string
  pollTitle: string
  voteUrl: string
  createdBy: string
}) {
  const { to, name, pollTitle, voteUrl, createdBy } = params

  const response = await fetch('https://api.sendgrid.com/v3/mail/send', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${process.env.SENDGRID_API_KEY}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      personalizations: [{ to: [{ email: to, name }] }],
      from: {
        email: process.env.SENDGRID_FROM_EMAIL || 'cameron@neuroprogeny.com',
        name: 'Neuro Progeny',
      },
      subject: `When are you available? ${pollTitle}`,
      content: [
        {
          type: 'text/html',
          value: `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="margin:0;padding:0;background:#F8FAFB;font-family:'Helvetica Neue',Arial,sans-serif;">
  <div style="max-width:560px;margin:0 auto;padding:40px 24px;">
    <div style="background:white;border-radius:16px;padding:32px;box-shadow:0 1px 3px rgba(0,0,0,0.06);">
      
      <!-- Logo -->
      <div style="text-align:center;margin-bottom:24px;">
        <div style="display:inline-block;width:48px;height:48px;background:#476B8E;border-radius:12px;line-height:48px;text-align:center;">
          <span style="color:white;font-size:20px;font-weight:bold;">NP</span>
        </div>
      </div>

      <h1 style="font-family:Georgia,serif;font-size:24px;color:#1E293B;text-align:center;margin:0 0 8px;">
        ${pollTitle}
      </h1>
      
      <p style="color:#64748B;text-align:center;margin:0 0 24px;font-size:15px;">
        ${createdBy} wants to find a time that works for everyone.
      </p>

      <p style="color:#1E293B;font-size:15px;line-height:1.6;">
        Hi ${name},
      </p>
      <p style="color:#1E293B;font-size:15px;line-height:1.6;">
        Please select the times you're available. It only takes a minute.
        Once everyone responds, you'll receive a calendar invite automatically.
      </p>

      <!-- CTA Button -->
      <div style="text-align:center;margin:32px 0;">
        <a href="${voteUrl}" 
           style="display:inline-block;background:#476B8E;color:white;padding:14px 40px;
                  border-radius:12px;text-decoration:none;font-weight:600;font-size:16px;">
          Select Your Availability
        </a>
      </div>

      <p style="color:#94A3B8;font-size:13px;text-align:center;">
        Or copy this link: <a href="${voteUrl}" style="color:#476B8E;word-break:break-all;">${voteUrl}</a>
      </p>
    </div>

    <p style="color:#94A3B8;font-size:12px;text-align:center;margin-top:24px;">
      Neuro Progeny  &bull;  Powered by NP Scheduler
    </p>
  </div>
</body>
</html>
          `.trim()
        }
      ]
    })
  })

  if (!response.ok) {
    const errText = await response.text()
    throw new Error(`SendGrid error: ${response.status} ${errText}`)
  }
}
